server:
  port: 40004

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
#    url: ENC(jwl+isoveIDH7Lkq65odEDnQ3bhZiqhhvsAOKEqwLL0r3+9L8Xc2//2Wv7DvGIGEd/ZNAmnYerw6wlarB3GusYYAqwBfcBqkSCXMDJTraGV4JAf/+7UQci3hsk5wZJI7x6wn8WSDR1UXwTXAOJEzjSriVifjhzHh)
#    username: ENC(hy2RQj/en0H+sZebqYHfrg==)
#    password: ENC(GfPTCPid6UXGjG4G1pH4xusGFGHiB7sK)
    url: jdbc:mariadb://localhost:3306/bigagoda
    username: root
    password: root
    hikari:
      idle-timeout: 60000
      minimum-idle: 0

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false

  mvc:
    async:
      request-timeout: -1
  jpa:
    hibernate:
      ddl-auto: update
agoda:
  key: ENC(IaqGs3hpll/ldG01Z/m/WLCX4uCUh9qgPijf4aEMlgbp5GuujOx3pJjqVZduiT1qDGzSv5PGkT4=)

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
