server:
  port: 40004

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ENC(FqlJT/cvrjrqdCBmXz1yUd/OHrO0bGmwg4a0KtU++uJogH6aIU9z2iFP2Tm8vgmhVr1MEAtCoAK3gGas2eO0eQBMQ6pmtUsEEM4CYRRcZJLSVNxVqwDN5d6a1hNQuIEC0BMee97NHxPTaFRpfP1zfJUj23Q7xfEn)
    username: ENC(hy2RQj/en0H+sZebqYHfrg==)
    password: ENC(GfPTCPid6UXGjG4G1pH4xusGFGHiB7sK)

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false

  mvc:
    async:
      request-timeout: -1
  jpa:
    hibernate:
      ddl-auto: update
agoda:
  key: ENC(IaqGs3hpll/ldG01Z/m/WLCX4uCUh9qgPijf4aEMlgbp5GuujOx3pJjqVZduiT1qDGzSv5PGkT4=)
