server:
  port: 40004

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ENC(jwl+isoveIDH7Lkq65odEDnQ3bhZiqhhvsAOKEqwLL0r3+9L8Xc2//2Wv7DvGIGEd/ZNAmnYerw6wlarB3GusYYAqwBfcBqkSCXMDJTraGV4JAf/+7UQci3hsk5wZJI7x6wn8WSDR1UXwTXAOJEzjSriVifjhzHh)
    username: ENC(hy2RQj/en0H+sZebqYHfrg==)
    password: ENC(GfPTCPid6UXGjG4G1pH4xusGFGHiB7sK)
    hikari:
      # 커넥션 대기: 길게 두지 말고 빠르게 실패
      connection-timeout: 30000          # 30s

      # 유휴/수명/핑: 네트워크/DB보다 조금 더 공격적으로
      idle-timeout: 300000               # 5m
      max-lifetime: 840000               # 14m (LB/프록시 idle보다 짧게)
      keepalive-time: 240000             # 4m (유휴 커넥션 주기 ping)

      # 최소 유지 커넥션: 0 금지 (버스트 대비)
      minimum-idle: 2                    # 코어·트래픽에 맞춰 2~min(최대풀/4)
      maximum-pool-size: 10              # DB 최대 연결/코어/동시성에 맞게 조정

      # 문제 추적용 (임시 켜서 원인 찾기)
      leak-detection-threshold: 30000    # 30s 이상 잡고 있으면 스택 로그

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false

  mvc:
    async:
      request-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
agoda:
  key: ENC(IaqGs3hpll/ldG01Z/m/WLCX4uCUh9qgPijf4aEMlgbp5GuujOx3pJjqVZduiT1qDGzSv5PGkT4=)
google:
  place:
    key: ENC(v7v4rrkogSR9xp8qyzaHro0CacaEEzfMChAZho0kvQMA8w3lEiqoMqgLd8FovV5u)

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

aws:
  s3:
    region: ENC(Mlzr8TwGGnqI4O1j4O4GGN8Ot9YvYtML)
    accessKey: ENC(3tm0nuy9RiaHWiyV/kdIU8UP9HazqAf9t01TaPvM4oE=)
    secretKey: ENC(e4NCzdo/LamGPgghXjQIwEXCkXMQ89LVj7/YuMJSklqNMBER/FwCH1G3wot6iEacaIPA82ZK2j0=)
    bucket-name: ENC(mgxgi2YUup1ZP3v7XkoqbQ/nv7SZF7rB)