server:
  port: 40004

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/ranku
    username: root
    password: root
  mvc:
    async:
      request-timeout: -1
  jpa:
    hibernate:
      ddl-auto: update